"""empty message

Revision ID: 39a8b03864d9
Revises: 3edd2abed14b
Create Date: 2025-01-29 19:09:36.869137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a8b03864d9'
down_revision = '3edd2abed14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especialistas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendly', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especialistas', schema=None) as batch_op:
        batch_op.drop_column('calendly')

    # ### end Alembic commands ###
