"""empty message

Revision ID: f46f78e8eaba
Revises: aaad18a66dc6
Create Date: 2025-02-11 15:47:19.306148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46f78e8eaba'
down_revision = 'aaad18a66dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disponibilidadMedico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_event_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disponibilidadMedico', schema=None) as batch_op:
        batch_op.drop_column('google_event_id')

    # ### end Alembic commands ###
